/**:
  ros__parameters:
    common:
      body_id: "body"
      imu_topic: "/livox/imu"
      lid_topic: "/livox/lidar"
      odom_id: "odom"
      time_sync_en: false
      visualization_frame: "livox_frame"
    filter_size_map: 0.5
    filter_size_surf: 0.5
    cube_side_length: 100.0
    #feature_extract_enable: false  
    interval: -1
    mapping:
      acc_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      det_range: 100.0
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      extrinsic_T: [-0.011, -0.02329, 0.04412]
      extrinsic_est_en: true
      fov_degree: 360.0
      gyr_cov: 0.1
    max_iteration: 3

    pcd_save_enable: true
    point_filter_num: 1
    preprocess:
      blind: 0.5
      lidar_type: 1
      scan_line: 4
      scan_rate: 10
      timestamp_unit: 3
    publish:
      dense_publish_en: false
      map_en: true
      path_en: true
      scan_bodyframe_pub_en: true
      scan_publish_en: true
    runtime_pos_log_enable: false  # for solve time logs
